In [9]:
import pandas as pd
df=pd.DataFrame({
    "Quantity":[2,3,5],
    "Price":[100,200,150],
})

df['Total Price']=df['Quantity']*df['Price']
df

   Quantity  Price  Total Price
0         2    100          200
1         3    200          600
2         5    150          750

In [10]:
df1=pd.DataFrame({"Salary":[25000,30000,35000,40000]})
df1['Normalized']=(df1.Salary-df1.Salary.min())/(df1.Salary.max()-df1.Salary.min())
df1

   Salary  Normalized
0   25000    0.000000
1   30000    0.333333
2   35000    0.666667
3   40000    1.000000

feature encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
gender=['Male','Female','Female','Male']
print(le.fit_transform(gender))

[1 0 0 1]

In [21]:
df=pd.DataFrame({"Date":['2023-01-01','2023-01-02','2023-01-03']})
df['Date']=pd.to_datetime(df['Date'])
df['Day']=df['Date'].dt.day
df['Month']=df['Date'].dt.month
df['Year']=df['Date'].dt.year

df

        Date  Day  Month  Year
0 2023-01-01    1      1  2023
1 2023-01-02    2      1  2023
2 2023-01-03    3      1  2023